pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'Namecheap FTP Credentials'  # Reference the variable group for FTP credentials
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y php-cli
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        php composer.phar install
      displayName: 'Install PHP and Composer dependencies'
      
    # Ensure that build artifacts are properly archived
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    # Publish artifacts to be used in the release stage
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - script: |
        sudo apt-get install -y lftp

        # Deploy the artifacts to the Namecheap FTP server
        lftp -e "
          set ftp:ssl-allow no;
          open -u $(ftpUsername),$(ftpPassword) $(ftpServer);
          lcd $(Build.ArtifactStagingDirectory);
          mirror -R ./ /public_html/;
          bye
        "
      displayName: 'Deploy to Namecheap FTP Server'
