pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  displayName: 'Build Stage'
  condition: eq(variables['Build.SourceBranchName'], 'development')
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: |
        sudo apt-get update
      displayName: 'Update Ubuntu'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - script: |
        sudo apt-get install -y git
        git config --global user.name "michaelakintayo7"
        git config --global user.email "michaelakintayo7@gmail.com"
        
        # Push the build artifacts to the main branch
        git checkout main
        git pull origin main
        git add -A
        git commit -m "Auto-commit from CI pipeline on $(Build.BuildId)"
        git push origin main
      displayName: 'Push artifacts to the main branch'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: eq(variables['Build.SourceBranchName'], 'deployment')
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - script: |
        sudo apt-get install -y lftp
        
        # Deploy the artifacts to the Namecheap FTP server
        lftp -e "
          set ftp:ssl-allow no;
          open -u chemManager@igetam.com,ShMoJaKa123 ftp.derightway.com;
          lcd $(Build.ArtifactStagingDirectory);
          mirror -R ./ /public_html/;
          bye
        "
      displayName: 'Deploy to Namecheap FTP Server'
