trigger:
- development  # Or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '5bb2315d-6a24-4f44-9f69-50511bf6e54d'
  kubernetesCluster: 'kubernetes-service-connection'
  dockerRegistryServiceConnection: 'docker-registry' # Docker Hub service connection name
  imageName: 'michaelakintayo7/docker-hub-repo'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'  # Ensure correct path to Dockerfile
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  azureResourceGroup: 'Group-6-Project-webapp'
  aksCluster: 'group6cluster'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y php-cli
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        php composer.phar install
      displayName: 'Install PHP and Composer dependencies'

    # Docker build and push
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageName)'
        dockerfile: '$(dockerfilePath)'
        tags: |
          latest
        buildContext: '$(Build.SourcesDirectory)'

    # Archive build artifacts if necessary
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: '$(azureSubscription)'  # Reference to your variable
        azureResourceGroup: '$(resourceGroup)'
        kubernetesCluster: '$(aksCluster)'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: './helm-chart'
        releaseName: 'myapp'
        overrideValues: 'image.repository=$(imageName),image.tag=latest'
