name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4  # or your desired PHP version

    - name: Install Dependencies
      run: |
        composer install

    - name: Run Build Script
      run: |
        # Add any custom build steps if needed
        echo "Build complete"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Directory where the built site is stored, modify as needed
        publish_branch: gh-pages
