trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

stages:
  # CI Stage
  - stage: Build
    displayName: 'Build Stage'
    jobs:
    - job: BuildJob
      displayName: 'Build Job'
      steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-xml php-mbstring
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar install
        displayName: 'Install PHP and Composer dependencies'

      - script: |
          echo Build steps go here
        displayName: 'Custom Build Steps'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifacts'
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)'
          artifactName: 'drop'
          publishLocation: 'Container'

  # CD Stage
  #- stage: Deploy
 #   displayName: 'Deploy Stage'
 #   dependsOn: Build
  #  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
   # jobs:
   # - deployment: DeployToAppService
    #  displayName: 'Deploy to Azure App Service'
    #  environment: 'Production'
     # strategy:
      #  runOnce:
       #   deploy:
        #    steps:
         #   - download: current
          #    artifact: drop
           # - task: AzureWebApp@1
            #  inputs:
             #   azureSubscription: 'Azure for Students'
              #  appType: 'webAppLinux'
               # appName: '<Your-App-Service-Name>'
               # resourceGroupName: 'Group-6-Project-webapp'
               # package: '$(System.ArtifactsDirectory)/drop'
