trigger:
  branches:
    include:
      - development  # Automatically trigger the pipeline on commits to the development branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: |
        sudo apt-get update
      displayName: 'Update system packages'

    # Ensure that build artifacts are properly archived
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    # Publish artifacts to be used in the deployment stage
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - script: |
        # Install ftp
        sudo apt-get install -y ftp

        # Connect to FTP server, delete existing content, and upload new artifacts
        ftp -inv $FTP_SERVER <<EOF
        user $FTP_USERNAME $FTP_PASSWORD
        cd /home/derikd/igetam.com
        # Delete the 'chemManager' directory if it exists
        quote SITE CHMOD 777 chemManager
        mdelete chemManager/*
        rmdir chemManager
        # Recreate the directory for new artifacts
        mkdir chemManager
        cd chemManager
        mput *
        bye
        EOF
      displayName: 'Deploy to FTP Server'
      env:
        FTP_USERNAME: 'chemManager@igetam.com'
        FTP_PASSWORD: 'ShMoJaKa123'
        FTP_SERVER: 'ftp.derightway.com'
