apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # This is where the image name is replaced
        ports:
        - containerPort: 80
