name: CI/CD Pipeline

# Trigger the pipeline on commits to the development branch
on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Update system packages
    - name: Update system packages
      run: sudo apt-get update

    # Archive build artifacts
    - name: Archive build artifacts
      run: |
        zip -r ${{ github.workspace }}/build_${{ github.run_id }}.zip .
    
    # Upload the artifacts to GitHub (Artifacts tab)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}/build_${{ github.run_id }}.zip

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy runs after build

    steps:
    # Checkout the repository again
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install lftp for FTP upload
    - name: Install lftp
      run: sudo apt-get install -y lftp

    # Deploy to FTP server using lftp
    - name: Deploy to Namecheap Server
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
      run: |
        lftp -u $FTP_USERNAME,$FTP_PASSWORD -e "set ftp:ssl-allow no; mirror -R ./ /; quit" $FTP_SERVER
